### ISSUE TITLE
License & Project Status

### ISSUE THREAD

**Issue by BrianOtto** [jakubtomsu/dungeon-of-quake#1]
Kudos, this is some amazing work!

I just discovered Odin recently and have been messing around with Raylib to learn the language.

This is exactly the type of project I was thinking of starting :)

What license is your work under?

Also, are you planning to get back to this development at some time in the future?

I wouldn't mind contributing and/or forking the code once I get more familiar with it, depending on what your plans and license are.

**Comment by jakubtomsu** [comment]
Hi, thanks!

I haven't really thought about the license at all. This isn't a commercial project, so I don't mind putting under a permissive license or even in a public-domain. Do you have any suggestions for an ideal license for this project? MIT license seems cool, but I don't really know much about software licensing in general :)

And yeah, this project has been stagnant for some time. I would really like to get back to it if I find some free time. I would like to improve the physics (the current implementation is just hacked together), some gameplay aspects and the level editor.
Your contributions are definitely welcome!

I've learned a few things about writing programs in Odin since I started this project, but it's still probably not a bad place to start.

Sorry for the late response.

**Comment by BrianOtto** [comment]
I would love it if you put everything in the public domain, but I don't want to tell you how you should license your work.

Did you create all the assets in the build directory yourself? If not, their license may affect what you can use for the project.

Otherwise, MIT is probably the one people understand the most. It's very permissive and compatible with nearly everything.

I personally like to use ISC. It's basically identical to MIT, but with simpler language. But that's just me.

I would be thrilled with any of those licenses!

As for contributing, cool, I am going to dig into the code a bit and see what I can help with.

Cheers!

**Comment by jakubtomsu** [comment]
Ok I added the license (71bf668a0b2ff078bf63d5131282152818f0544f). I chose both MIT and Public Domain, same as STB libraries (https://github.com/nothings/stb). Hope that suits your needs.
